import { Navbar } from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { WalletContextProvider } from "@/providers/context";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-20">
        <WalletContextProvider>
          <Navbar />
          {children}
          <Footer/>
        </WalletContextProvider>
      </body>
    </html>
  );
}
